// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cmd} from '../models';

export function GetConfig(arg1:string):Promise<cmd.Config>;

export function ReadFile(arg1:string):Promise<string>;
